### PR TITLE
Added feature to darken or lighten the current color by a pct.

### PR DESCRIPTION
**Pull request by johnpapa**
In response to this issue to darken one lighten a color. 

https://github.com/johnpapa/vscode-peacock/issues/158

Feedback welcome

### CODE REVIEW

**Comment by johnpapa** [comment]
I’m currently thinking that the percentages should be a setting. Soo when you darken or lighten a color it always goes up or down by a specific amount. I hadn’t originally thought of making this a number. But then it has two challenges

1. We would need logic to restrict it from 1 to 100 pct. 
2. Anything over 25% can very easily go to white or black

This is why I changed the code in the PR to use an enumeration for 5 to 25 percent in increments of 5. 

Alternatively we could make this a number without an enum and restrict to 1 to 25 pct. again needing additional logic to restrict it. 

I welcome feedback on this @musicfuel or any others.

**Comment by johnpapa** [comment]
I also think a keyboard shortcut would be nice to increments or decrement. Any thoughts on this?

**Comment by johnpapa** [comment]
I discovered a feature that allows restricting a config property to a range. I changed the setting so it now accepts a number 1 to 20. even 25 felt too much.with 1 to 20 it gives a decent amount of control over this. 

Im considering reducing this to 1 to 10.

**Comment by musicfuel** [comment]
A keyboard shortcut would be cool for quick changes, but I wonder if it would be used enough to justify a shortcut.

It’s cool that the percentage can be constrained.  That is what I was getting at with my suggestion of an enum with words as opposed to numbers. I think the solution you came up with is a really good one.

**Comment by johnpapa** [comment]
I hear you - not sure if it would be used a lot, so I decided to make it a multi key combo. I like using that instead of constantly opening the CMD palette.

I was not aware  that ranges could be implemented. At first I did an enum, but I think the range is pretty slick.

Unless I find any issues with this PR, or any new feedback comes in , I'll merge this over the weekend.

**Pull request merged**
