### PR TITLE
docs: document how to set default colors

### LINKED ISSUE #235: Document how to set default colors
Setting `peacock.color` or `peacock.remoteColor` in the user settings.json can be done manually. If set, peacock will use that color as the default color to colorize VS Code. 

This should be documented in the readme, along with considerations.

Considerations:
- this can only be set or unset manually. 
- this will make every vs code instance that doesnt have a color in their workspace use the default color
- this could be annoying, use wisely (this is why it is not set via any command)

Why does this exist at all then?
- Good question. The setting is important in the workspace and vs code merges settings across user and workspace settings. So it must exist in all of them, even tho peacock really mostly cares about the workspace. This is why the user setting is not set by default.

### PR DESCRIPTION
**Pull request by santoshyadav198613**
Fixes #235

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
Hi @johnpapa can you review once.

**Comment by johnpapa** [comment]
Hi. Thanks for the PR. 

I took a quick look and this copies a lot of my notes to the docs. But I wonder if it should be filled out with any more details. Does it explain it well?

**Comment by santoshyadav198613** [comment]
Ok I will work on it.

**Comment by johnpapa** [comment]
closing. can resubmit later if you like once changes are made

**Pull request closed without merging**
