### PR TITLE
Enable your extension to run on VS Code for the web

### PR DESCRIPTION
**Pull request by tanhakabir**
Hey @johnpapa! 👋

I'm part of the VS Code team and we recently launched VS Code for the web with [github.dev](https://docs.github.com/en/codespaces/developing-in-codespaces/web-based-editor)! You can read the full guide for extension authors creating and migrating extensions here: [Web Extensions
](https://code.visualstudio.com/api/extension-guides/web-extensions)

In hopes to help you migrate I helped make the changes necessary to make your extensions work on the web.

The changes I made:
- Modify webpack bundling to create web and desktop friendly versions of your extension
- Add the necessary dependencies for web bundling
- Add the `browser` entry point to your `package.json` to link to the web-friendly compiled extension
- Add some folders/files to ignore in your `.gitignore` and `.vscodeignore`
- Add launch configuration for launching your extension in a web extension host

You can test your extension with a launch configuration or `vscode-test-web`. [Learn more on the docs.](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension)

### CODE REVIEW

**Comment by tanhakabir** [comment]
cc @egamma

**Comment by johnpapa** [comment]
Thank you for the PR! I 100% want to support github.dev with Peacock.

I’m not sure I follow the changes. Seems like the change in package.json helps it launch in the browser, but there are also a lot of testing related changes and webpack changes/additions. Can you help me understand what those are for?

**Comment by tanhakabir** [comment]
@johnpapa no worries! There's more detailed information on [Web Extensions
](https://code.visualstudio.com/api/extension-guides/web-extensions) but essentially for an extension to work on the browser it needs to be compiled into a single JS file to be loaded on vscode in the browser. This web friendly version must also only use libraries available in the browser, so none of the core node libraries like `fs` and `path`. 

To do this I modified your webpack config file to output another web friendly single file compilation of your extension that has the environment of `webworker` to work in the browser rather than `node` to work in VS Code.

To let VS Code k now your extension will work in the browser, I added a `browser` entry point to point to the file, this is the same as `main` for VS Code on the machine.

I also upgraded some of the old dependencies and I used `vscode-test-web` to launch your extension in a Chromium instance and wanted to ignore all the files generated by that method. You can learn more about how to verify your extension works here: [Web Extension Tests](https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-tests)

I realized I made one error in the launch config to point to the appropriate web version. I'm fixing that now

**Comment by johnpapa** [comment]
I am having difficulty verifying that this works. I'll reach out directly so we can set up a time to connect.

**Review by johnpapa — APPROVED** [review]

**Comment by johnpapa** [comment]
@all-contributors please add @tanhakabir for code

**Pull request merged**
