### PR TITLE
Add alpha support details to input

### LINKED ISSUE #293: Alpha colors incompatable.
**Versions (please complete the following information):**

- Win10
- VS Code 1.38.1
- Peacock 3.1.5

**Describe the bug**
When using CSS alpha colors, the auto-contrast for menu & icons does not work.

**To Reproduce**
```json
"peacock.favoriteColors": [
        {
            "name": "Nord: Auroa Red",
            "value": "#bf616a4d"
        },
        {
            "name": "Nord: Auroa Orange",
            "value": "#d087704d"
        },
        {
            "name": "Nord: Auroa Yellow",
            "value": "#ebcb8b4d"
        },
        {
            "name": "Nord: Auroa Green",
            "value": "#a3be8c4d"
        },
        {
            "name": "Nord: Auroa Purple",
            "value": "#b48ead4d"
        },
etc
```
**Expected behavior**
The menu & left-icons to be legible 

**Screenshots**
You can see the 'base' color in the window behind the dark-orange peacock-themed with alpha.
vscode-peacock-bug-alpha

**Additional context**
Kinda low priority.  Quickest way is just post instructions how to set the menu foreground colors.
A good comprimise is to add optional fields to each theme color:
```json
"peacock.favoriteColors": [
        {
            "name": "Nord: Auroa Red",
            "value": "#bf616a4d",
            "menu": "white",
            "icon": "lemon"
        },
```

Thanks for your great work.

### PR DESCRIPTION
**Pull request by musicfuel**
This adds documentation recommending against the use of the alpha channel when entering colors to close #293.

### CODE REVIEW

**Comment by musicfuel** [comment]
@johnpapa As I was writing this it occurred to me that we could also remove the alpha capable input formats from the table and alter the input validation such that if a color with alpha is entered it will be considered not valid. That said, it feels like a bit of a breaking change and may be a bit of a strong reaction to this.

Thoughts?

**Comment by johnpapa** [comment]
Thanks for thinking this through. I agree that that may be too strong. Instead, how about we just discourage it with the FAQ . I don’t think a lot of people are trying this at this point, given that we have 350,000 users and we just heard about this. Therefore I’d like to air on the side of less of a disruption. If we get a stronger response in the future, we could consider locking down the alpha. Do you agree?

**Comment by musicfuel** [comment]
I completely agree. Is this good as is or would you like it moved down to a FAQ question further down the doc? I could also add a FAQ with a link back to this area, but the two are pretty close already.

**Comment by johnpapa** [comment]
I think a link in the FAQ is a good idea.

**Comment by johnpapa** [comment]
Thank you

**Pull request merged**
