### PR TITLE
Feature/status bar debugging color

### LINKED ISSUE #271: [Feature] Add debuggingBackground color
The extension currently does not modify the background colour of the status bar in debug mode, i.e. `statusBar.debuggingBackground`.

It would be great if this could be added to the object of generated colours, perhaps with a different shade of (or complementary of) the default background.

### PR DESCRIPTION
**Pull request by musicfuel**
closes #271 

## Purpose

Adds color support for the debugging colors that can be shown in the status bar when in an active debug session. Previously, Peacock would not manage these color settings so a debug session would revert to the current theme. That color may not work well with the current Peacock scheme as a minor concern, but more importantly could cause confusion where one or more windows had active debug sessions because they would all have the same status bar color.

## Checklist of changes included

- [x] CHANGELOG updated
- [x] README updated
- [x] Tests updated/added
- [x] Prettier formatting
- [x] console.log removed
- [x] Dead code removed
- [x] Unnecessary comments removed
- [x] Images updated (if applicable)
- [x] Version updated everywhere

### CODE REVIEW

**Comment by musicfuel** [comment]
@johnpapa I've finally gotten to this request from a couple weeks ago and after returning to this project after quite a bit away I can see that lots of nice changes have been made. That said, I am struggling a bit and may need some advice from you.

First, no matter what I try locally on the project I cannot get my tests to run. I've tried running from the command line only, running from the Extensions Test launch configuration, and doing both using insiders and stable VS Code. No matter what I try, something errors out within VS Code and the extension testing process that prevents the tests from successfully running. When using the launch configuration the extension window will open, but then close pretty quickly with no insight into why it is failing.

Given the above, I am flying blind a bit on the 3 tests I wrote so I don't know if they work as expected or not to this point. I thought I could perhaps use the PR status here to at least run the tests, but then I hit another roadblock with the Azure Static Web Apps CI/CD because I don't have a token for it. I am pretty sure I could fix this by setting up a token of my own in my fork with the same name, but I just want to check with you first if there is another way to address this. As is, I'm not sure how well PR status checks will work with any PRs that don't have a token for Azure Static Web Apps themselves. As an example, it looks like status checks for #402 and this PR are both failing because of the token issue.

**Comment by musicfuel** [comment]
@johnpapa I know the status checks will not pass, but am moving this to ready for review because at this time I don't have any further work I can do on it until I get the testing setup resolved.

**Comment by johnpapa** [comment]
Thanks. I'll take a look and see if I can get tests to work locally on yours. One thing that comes to mind is the the engine version ... I have had issues with that in the past.

**Comment by johnpapa** [comment]
I've been unable to get tests to work anymore. First, they take forever ... like 20 minutes or more. Second, anywhere from 20 to 35 fail at a time. Some due to timeouts and some due to errors on code not in my project (ex: getFileName is known).

I need to ask for help on this ... til then, I will keep manually looking

**Comment by johnpapa** [comment]
@musicfuel It seems this change the debugging bar color without giving the user a choice.

What do you think about making this a setting? Otherwise this is an unexpected change.

Would you be up for adding a `manageDebugColor` setting for this? (or whatever a better name may be). Default it to same behavior as current release (meaning dont let it change the color)

**Comment by musicfuel** [comment]
@johnpapa I got the notification of the close on this and it jolted me into remembering that I needed to get back to you. I see that you renamed the `master` branch to `main` and I am assuming that action closed this, but I am not sure if it was automatic or you chose to simply close this one.

Even though I thought about it, I originally did not make this a setting just to avoid further expanding the settings for the plugin. I would be happy to spend a little more time to make this into a setting if you prefer.

**Comment by johnpapa** [comment]
Thanks James. Yeah it looks like it auto closed it when I renamed to main. Sorry about that. 

I think a setting would be best. I hear you on adding settings - but I think it's warranted in this case as it would be an abrupt change for existing users. We now have 890k installations - which is astounding to me. Given the wide use I prefer not to disrupt there current experience but instead have an opt in experience. 

Thank you so much for all of your contributions. Peacock is better because of you and your help.

**Comment by musicfuel** [comment]
Sounds good. I will get the changes in place and I agree on the opt-in experience being preferred.

**Pull request closed without merging**
