### PR TITLE
Update icon based on original sketch

### PR DESCRIPTION
**Pull request by musicfuel**
I appreciate the work by @josephrexme, but just wanted to offer another take on the extension icon. I drew inspiration from the at the original idea generation sketch:

peacock-sketchnote

I formalized that a bit around some concentric circles, used an on-brand vscode blue for the majority of the body, and then color shifted the tail feathers to go along with the concept:

peacock-icon

This is sized at 256x256 to support retina screens.

### CODE REVIEW

**Comment by josephrexme** [comment]
Looks great @musicfuel

**Comment by johnpapa** [comment]
ooooh. i like that it looks like my hand sketch (but better). 

@josephrexme and @musicfuel - do you think the logo should have the name Peacock in it?

**Comment by josephrexme** [comment]
I think it's great without the name since the names are placed just beside the icon in VSCode

**Comment by johnpapa** [comment]
thanks!

**Comment by musicfuel** [comment]
Awesome. I'm a bit late, but I agree with @josephrexme that the name is not needed.

**Comment by johnpapa** [comment]
thanks - i'll credit you both in the next readme and version

**Pull request merged**
