### PR TITLE
Add "Go Cyan" favorite color

### PR DESCRIPTION
**Pull request by Calinou**
The color was taken from the https://golang.org/ favicon which represents the Go mascot. This was done to provide a color that's easy to distinguish from other colors such as React Blue.

### CODE REVIEW

**Comment by johnpapa** [comment]
Thanks for the PR.

I looked for the color and didnt see one listed anywhere. I did a color match on the gopher from a few images and see #6AD2FD come up most often. 

How can we find the right color?

**Comment by bketelsen** [comment]
Either the gopher blue r the light blue would be appropriate.  Definitely blue though.

**Comment by johnpapa** [comment]
Here is how they look compared to React Blue

image

The blue one (0add80) is very close to react's blue. Biggest difference is that it must be a little darker as the font is now white.

The other blue is more distinguishable.

Which color do you like of the 2 on the right for Go? 

Also, is it still worth it? (im open to it)

**Comment by Calinou** [comment]
I prefer the bottom-right one as it's easier to distinguish from React Blue :slightly_smiling_face:

**Comment by johnpapa** [comment]
ok - make the change please to the PR, and we can proceed to merge

**Comment by Calinou** [comment]
@johnpapa Done :slightly_smiling_face:

**Comment by johnpapa** [comment]
published in 2.3.0
https://twitter.com/John_Papa/status/1137719328193863680

**Pull request merged**
