### PR TITLE
Added usage instructions

### PR DESCRIPTION
**Pull request by chmac**
This had me stumped. Maybe it's obvious to other folks, but I struggled to figure out what to actually do once the plugin was installed. I assumed my projects would be automatically coloured for me. Figured this might help other folks get there quicker. :-)

### CODE REVIEW

**Comment by chmac** [comment]
PS> Thanks, this is an awesome package!

**Comment by johnpapa** [comment]
Hi - thanks for the PR. I'd much rather link to the docs for this. The radme has a link to the extensive documentation for Peacock. If you feel the README cna make this clearer to look there, please feel free to open a PR to do that. Thanks!

**Comment by johnpapa** [comment]
> PS> Thanks, this is an awesome package!

Thank you!

**Comment by chmac** [comment]
@johnpapa Sure, I can see there would be other ways to surface the info. My experience was that I read the readme, read the docs, and I just didn't get it. I assumed I would install the plugin and my projects would become coloured. I was looking at the screen and scratching my head. I read and re-read the docs. Config options, etc, etc. The big thing that was missing for me was the fact that I need to manually assign colours to each project. Maybe there's a simpler way to surface that to folks immediately, or maybe it's immediately obvious to the other 1.1m users of the plugin and I'm the only idiot! 😆 

I'm happy to try a different approach in the readme if you think that would help, or if you feel like this is not worth pursuing, also happy to leave it. I've now figured it out, so my personal issue has been solved! :-)

**Pull request closed without merging**
